apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 30000 #se não declarar, será atribuído aleatoriamente
  selector:
    app: portal-noticias        